### ISSUE TITLE
null в заполнителях

### ISSUE THREAD

**Issue by colshrapnel** [digitalstars/DataBase#1]
Оригинальные заполнители PDO (и mysqli) отправляют в БД null, если передано значение null.
И это очень логичное поведение. 
Было бы неплохо видеть его и в этой библиотеке. 
То, есть, скажем, функцию getValueIntType я бы предложил переписать так

    private function getValueIntType($value) {
        if (is_integer($value))
            return $value;
        if (is_numeric($value) || is_bool($value)) {
            return (int)$value;
        }
        if (is_null($value)) {
            return 'null';
        }
        throw new Exception($this->createErrorMessage('integer', $value));
    }

**Comment by digitalstars** [comment]
Можете кинуть pull request

**Comment by colshrapnel** [comment]
С удовольствием. А это вам нигде не поломает обратную совместимость?

**Comment by digitalstars** [comment]
Может и сломает, но к этому не привыкать, починится
