### ISSUE TITLE
Нарушение публичного контракта PDO

### ISSUE THREAD

**Issue by colshrapnel** [digitalstars/DataBase#2]
Прекрасная библиотека и прекрасное развитие идеи именованных плейсхолдеров.
И я хотел бы рекомендовать её к использованию, но предвижу критику из-за нарушения публичного контракта PDO, а конкретнее - LSP: "Функции, которые используют базовый тип, должны иметь возможность использовать подтипы базового типа, не зная об этом".    
То есть взять и подставить DataBase вместо PDO не получится. 
С одной стороны это не то чтобы проблема, но с другой все-таки ограничивает обрасть применения.

Нет ли в планах разделить PDO и DataBase, сделав PDO зависимостью для DataBase, применив старое доброе #prefer composition over inheritance#?

**Comment by digitalstars** [comment]
PDO и DataBase были разделены в отдельной ветке. PDO в ней является зависимостью для DataBase.

**Comment by digitalstars** [comment]
С обновлением 1.1.0 и переходом на php 8.0 теперь есть только ветка master, где библиотека наследуется от PDO
